#!/bin/bash
#
# Render a Markdown file to generate a PDF.

set -eu -o pipefail

if [[ "$#" != 3 ]]; then
    echo "Usage: $0 <subdir> <file>.md <revision-date>" >&2
    echo "Example: $0 Cut_Lists 'Interior Panels.md' 2026-01-17" >&2
    exit 1
fi

cd "$(dirname "$0")/.."

INPUT_DIR="$1"
INPUT_FILE="$2"
REVISION_DATE="$3"

OUTPUT_FILE="${INPUT_FILE/%.md/.pdf}"
export FOOTER="Revised $REVISION_DATE"

declare -a flags
flags=(pandoc -d ../render/pandoc-defaults.yaml -H ../render/typst-header.typ)
flags+=("'$INPUT_FILE'" -o "'$OUTPUT_FILE'")
flags+=(-H '<(echo "#set page(footer: context [#if calc.even(here().page()) [#h(1fr) $FOOTER] else [$FOOTER #h(1fr)]])")')

docker run -it --rm \
       -v "$PWD":/s \
       -w "/s/$INPUT_DIR" \
       -e FOOTER \
       -e TYPST_FONT_PATHS=/s/render/Carlito \
       --entrypoint=/bin/sh \
       pandoc/typst:3.8.3 \
       -c \
       "${flags[*]}"



