#!/bin/bash
#
# Render a Markdown file to generate a PDF.

set -eu -o pipefail

if [[ "$#" != 1 || ! -f "$1" ]]; then
    echo "Usage: $0 <path/to/file>.md" >&2
    echo "Example: $0 'Cut_Lists/Interior_Panels_Cut_List.md'" >&2
    exit 1
fi

INPUT="$(realpath "$1")"

CONTAINER="$(head -1 $(dirname $(realpath "$0"))/.container)" # Must match ./all!
cd "$(dirname "$0")/.."

# Delete any previous renderings of DXFs that happened before the
# newest file in render/ was touched, to avoid using outdated cached
# files when the pipeline changes.
[[ -d .rendered-dxfs ]] && find .rendered-dxfs/ -type f \
     ! -newer "$(find render -type f -printf '%T@ %p\n' | sort -nr | head -1 | cut -d' ' -f2-)" \
     -delete

export TZ="America/Los_Angeles"

function capitalize() {
    local orig="$1"
    local ret="${orig/.md/}"
    read -ra words <<< "${ret//_/ }"
    echo "${words[*]^}"
}

INPUT_FILE="$(basename "$INPUT")"
INPUT_DIR="$(dirname "$(realpath --relative-to="$PWD" "$INPUT")")"
TITLE="$(capitalize "$INPUT_DIR") \\ $(capitalize "$INPUT_FILE")"

export DEBUG="" # Set to non-empty to debug subprocess (pandoc/typst/qcad) failures.
RUNNER="$(type -p docker || type -p podman)"
function dockerRun() {
    local -a debug_flags
    [[ -n "$DEBUG" ]] && debug_flags+=(-e DEBUG=1 -e QT_LOGGING_RULES="*.debug=false;qt.*.debug=false;qt.*.warning=false")
    "$RUNNER" run --rm \
              -v "$PWD":/s:z \
              -w "/s/$INPUT_DIR" \
              -e FOOTER \
              -e TYPST_FONT_PATHS=/s/render/Carlito \
              "${debug_flags[@]}" \
              --entrypoint=/bin/bash \
              "$CONTAINER" \
              -c \
              "$@"
}

RELATIVE_RENDER_PATH="$(realpath --relative-to="$INPUT_DIR" "$PWD/render")"

declare -a common_flags
common_flags=(pandoc -d "${RELATIVE_RENDER_PATH}/pandoc-defaults.yaml" --template "${RELATIVE_RENDER_PATH}/typst-header.typ")
common_flags+=("--lua-filter=/s/render/dxf.lua")

# Extract from $INPUT any images it embeds, to account for in the last-revision timestamp.
# Needs to be a dockerRun separate from the typst invocation because the container doesn't have git.
export TEMPTYP=".TEMP.$$.typ"
extract_out="$(dockerRun "trap 'rm -f ${TEMPTYP}' EXIT; \
                         export DXF_DEPS=true; \
                         ${common_flags[*]} \
                  --to typst '$INPUT_FILE' -o ${TEMPTYP} \
        && typst compile --root /s -f pdf --deps /dev/stdout ${TEMPTYP} /dev/null | \
        `# Poor-man's jq to parse out deps' paths from typst json output.` \
        sed -e 's/^{\"inputs\":\[//' -e 's/]}$//' -e 's/^\"//' -e s'/\"$//' -e 's/\",\"/\n/g' | \
        `# Strip leading ../ to get back to repo-root-relative paths.` \
        sed -e 's#^\(\.\./\)*##' | \
        grep -v \"$TEMPTYP\" | \
        sort -n")" \
    || { echo "$0: failed extracting embedded images from $INPUT" >&2; exit 1; }
unset TEMPTYP
mapfile -t IMAGE_PATHS < <(printf '%s' "$extract_out")

last_modification="$(git log -1 --format="%cd|%ct" --date=format:"%Y-%m-%d %H:%M:%S" -- "${INPUT}" "${IMAGE_PATHS[@]}")"
IFS='|' read -r REVISION_DATE CREATION_TIMESTAMP <<< "${last_modification:-0000-00-00 00:00:00|0}" # Handle new .md files that have no git log yet.
OUTPUT_FILE="${INPUT_FILE/%.md/.pdf}"
if [[ -n "${RENDER_GO_EMIT_TIMESTAMPS:-}" ]]; then # Set in ./all.
    echo "$REVISION_DATE $1"
fi
export FOOTER="Revised $REVISION_DATE"

declare -a flags
flags=("${common_flags[@]}")
flags+=("--pdf-engine-opt=--root=/s")
flags+=("'$INPUT_FILE'" -o "'$OUTPUT_FILE'")
flags+=(-H '<(echo "#set page(footer: context { if counter(page).get().first() > 0 [$FOOTER #h(1fr) [#counter(page).display() / #counter(page).final().first()]] })")')
if ! grep -qF '#title-page[' "$INPUT"; then
    # No custom title-page, create a default one.
    flags+=(-V "title:\"$TITLE\"")
fi
# Make re-runs idempotent; typst embeds the "current" time into the .pdf, so set that "current" time to the last modification time of the input file.
flags+=("--pdf-engine-opt=--creation-timestamp=$CREATION_TIMESTAMP")

dockerRun "${flags[*]}"
